repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black
        language: system
        types: [python]
        exclude: (^|/)migrations/
        args: ['--line-length=120']

      - id: isort
        name: isort
        entry: poetry run isort
        language: system
        types: [python]
        exclude: (^|/)migrations/
        args: ['--profile', 'black']

      - id: flake8
        name: flake8
        entry: poetry run flake8
        language: system
        types: [ python ]
        exclude: (^|/)migrations/
        args: ['--max-line-length=120', '--extend-ignore=D104,D100,B008,W503,VNE001']

      - id: mypy
        name: mypy
        entry: poetry run mypy
        language: system
        types: [ python ]
        exclude: (^|/)migrations/
        args: ["--ignore-missing-imports"]
