services:
  db:
    image: postgres:16.8-alpine
    container_name: postgres_container
    environment:
      POSTGRES_DB: time_tracker_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  redis:
    image: redis:8-alpine
    container_name: redis_container
    ports:
      - "6379:6379"

  backend:
    build: .
    container_name: tracker_container
    command: >
      sh -c "python working_time_tracker/manage.py migrate &&
             python working_time_tracker/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data:
