# Generated by Django 5.2 on 2025-06-09 14:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_project_task_track_userextension_delete_testexample"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="task",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("TO_DO", "To Do"),
                    ("REJECTED", "Rejected"),
                    ("COMPLETED", "Completed"),
                    ("ON_HOLD", "On Hold"),
                    ("IN_PROGRESS", "In Progress"),
                    ("IN_REVIEW", "In Review"),
                    ("IN_QA", "In QA"),
                ],
                default="TO_DO",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="track",
            name="status",
            field=models.CharField(
                choices=[
                    ("TO_DO", "To Do"),
                    ("REJECTED", "Rejected"),
                    ("COMPLETED", "Completed"),
                    ("ON_HOLD", "On Hold"),
                    ("IN_PROGRESS", "In Progress"),
                    ("IN_REVIEW", "In Review"),
                    ("IN_QA", "In QA"),
                ],
                default="ON_HOLD",
                max_length=20,
            ),
        ),
    ]
