# Generated by Django 5.2 on 2025-06-12 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_alter_project_created_at_alter_task_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="track",
            name="status",
            field=models.CharField(
                choices=[
                    ("TO_DO", "To Do"),
                    ("REJECTED", "Rejected"),
                    ("COMPLETED", "Completed"),
                    ("ON_HOLD", "On Hold"),
                    ("IN_PROGRESS", "In Progress"),
                    ("IN_REVIEW", "In Review"),
                    ("IN_QA", "In QA"),
                ],
                max_length=20,
            ),
        ),
    ]
