# Generated by Django 5.2 on 2025-05-29 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0004_remove_task_user_task_assignee_task_reporter_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="is_completed",
        ),
        migrations.RemoveField(
            model_name="task",
            name="is_in_progress",
        ),
        migrations.AddField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("TO_DO", "To Do"),
                    ("IN_PROGRESS", "In Progress"),
                    ("IN_REVIEW", "In Review"),
                    ("IN_QA", "In QA"),
                    ("REJECTED", "Rejected"),
                    ("COMPLETED", "Completed"),
                ],
                default="TO_DO",
                max_length=20,
            ),
        ),
    ]
