# Generated by Django 5.2 on 2025-06-03 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "tracker",
            "0005_remove_task_is_completed_remove_task_is_in_progress_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=0.0004940711462450593
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="task",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=0.0004940711462450593
            ),
            preserve_default=False,
        ),
    ]
